### ISSUE TITLE
No latest tag for i2b2-pg

### ISSUE THREAD

**Issue by hsolbrig** [waghsk/i2b2-quickstart#2]
There isn't a 'latest' tag in the docker store for i2b2/i2b2-pg, meaning that the last script doesn't work.

**Comment by waghsk** [comment]
Yes. You are right.

The automatic docker generation pipeline is somehow failing to add the
latest tag.
Meanwhile you can use the tag release-v1.7.09.0001 instead of latest.
That should work

**Comment by waghsk** [comment]
fixed.
